import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";

const notserifbengali = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin" , "bengali"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${notserifbengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
          <div className="mt-20">      <Marquee></Marquee></div>
        {children}
        </body>
    </html>
  );
}
